### PR TITLE
fix up virtual topic consumer migration test to ensure demand and wai…

### PR DESCRIPTION
**Pull request by gtully**
…t for mesh formation

### CODE REVIEW

**Comment by gaohoward** [comment]
@goldmann Hi Marek can you handle this? thx.

**Comment by gaohoward** [comment]
@goldmann I guess this one needs to be scheduled first. :)

**Comment by goldmann** [comment]
Correct, every change should be reflected in JIRA and scheduled.

**Comment by gaohoward** [comment]
+1

**Comment by goldmann** [comment]
I'll also close this PR, because it's opened against my fork and not the correct repository.

**Pull request closed without merging**
